[workspace]
members = [
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "1.0"
eth-binary-tree = {git = "https://github.com/varun-doshi/eth-binary-tree.git",branch = "main"}