[package]
version = "0.1.0"
name = "binary-tree-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.0.0"
eth-binary-tree = {git = "https://github.com/varun-doshi/eth-binary-tree.git",branch = "main"}

